# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: paspartout-api 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "paspartout-api"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["wout"]
  s.date = "2014-02-22"
  s.description = "An abstraction layer for the Paspartout API"
  s.email = "wout@woutfierens.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/paspartout-api.rb",
    "paspartout-api.gemspec",
    "spec/helper.rb",
    "spec/paspartout-api_spec.rb"
  ]
  s.homepage = "http://github.com/wout/paspartout-api"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.9"
  s.summary = "An abstraction layer for the Paspartout API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<htmlentities>, ["~> 4.3.1"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.12.0"])
      s.add_runtime_dependency(%q<hashie>, ["~> 2.0.5"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.8.2"])
    else
      s.add_dependency(%q<htmlentities>, ["~> 4.3.1"])
      s.add_dependency(%q<httparty>, ["~> 0.12.0"])
      s.add_dependency(%q<hashie>, ["~> 2.0.5"])
      s.add_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<simplecov>, ["~> 0.8.2"])
    end
  else
    s.add_dependency(%q<htmlentities>, ["~> 4.3.1"])
    s.add_dependency(%q<httparty>, ["~> 0.12.0"])
    s.add_dependency(%q<hashie>, ["~> 2.0.5"])
    s.add_dependency(%q<rspec>, ["~> 2.14.1"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<simplecov>, ["~> 0.8.2"])
  end
end

